os:
  - linux

language: go

go:
  - "1.10.x"

install: true

sudo: required

services:
  - docker

env:
  - VERSION=0.1

matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_deploy:
  - git config --local user.name "hunterlong"
  - git config --local user.email "info@socialeck.com"
  - git tag "v$VERSION" --force
deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file:
      - "build/balancebadge-osx-x64"
      - "build/balancebadge-osx-x32"
      - "build/balancebadge-linux-x64"
      - "build/balancebadge-linux-x32"
      - "build/balancebadge-windows-x64.exe"
      - "build/balancebadge-windows-x32.exe"
    skip_cleanup: true

notifications:
  email: false

before_install:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then travis_wait 30 docker pull karalabe/xgo-latest; fi

before_script:
  - go get github.com/stretchr/testify/assert
  - go get github.com/karalabe/xgo
  - go get
  - go install

script:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then /bin/bash -c ./build.sh; fi
  - curl -s -X POST $DOCKER > /dev/null